In [1]:
import numpy as np
#np.unique and set()

In [2]:
name=np.array(["Bill","Joe","Will","Joe"])


In [3]:
np.unique(name)

array(['Bill', 'Joe', 'Will'], dtype='<U4')

In [5]:
a=np.array([1,2,3,3,3,4,5,2,3,7,6,8,9])
set(a)

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [6]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
values=np.array([6,0,0,3,2,5,6])
np.in1d(values,[6,3,5,2])

array([ True, False, False,  True,  True,  True,  True])

In [13]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
y=np.array([5,6,2,7,8,9,1,2,13,14,2,5])

y

array([ 5,  6,  2,  7,  8,  9,  1,  2, 13, 14,  2,  5])

In [11]:
np.unique(y)

array([ 1,  2,  5,  6,  7,  8,  9, 13, 14])

In [12]:
np.intersect1d(x,y)

array([1, 2, 5, 6, 7, 8, 9])

In [16]:
np.union1d(x,y)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 13, 14])

In [17]:
np.in1d(x,y)

array([False,  True,  True, False, False,  True,  True,  True,  True,
        True])

In [19]:
np.setdiff1d(x,y)

array([0, 3, 4])

In [20]:
np.setxor1d(x,y)

array([ 0,  3,  4, 13, 14])

In [21]:
arr=np.arange(10)

In [22]:
np.save("x",x)

In [23]:
np.load("x.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
c=np.random.randn(10)

In [25]:
c

array([ 0.81179366,  0.00615291,  0.09005118,  2.19580906, -0.45610392,
       -2.11551898,  0.51790844,  0.56517298, -0.74534852, -0.88237774])

In [31]:
np.savez("arrays_archive.npz",a=c,b=arr)

np.savez_compressed("arrays_archive.npz",a=c,b=arr)

In [32]:
npz=np.load("arrays_archive.npz")


In [33]:
npz["a"]

array([ 0.81179366,  0.00615291,  0.09005118,  2.19580906, -0.45610392,
       -2.11551898,  0.51790844,  0.56517298, -0.74534852, -0.88237774])

In [34]:
npz["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a=np.random.randint(1,7,6).reshape(2,3)

In [45]:
a

array([[5, 2, 2],
       [3, 6, 6]])

In [46]:
b=np.random.randint(1,9,6).reshape(3,2)

In [47]:
b

array([[3, 4],
       [8, 2],
       [1, 1]])

In [48]:
a.dot(b)

array([[33, 26],
       [63, 30]])

In [49]:
np.dot(a,b)

array([[33, 26],
       [63, 30]])

In [50]:
np.dot(a,np.ones(3))

array([ 9., 15.])

In [53]:
a @ np.ones(3)

array([ 9., 15.])

In [92]:
from numpy.linalg import inv,qr,det,eig,pinv

In [117]:
x=np.random.randint(1,9,20).reshape(2,2,5)
x

array([[[4, 3, 5, 8, 4],
        [7, 1, 2, 3, 1]],

       [[5, 4, 2, 3, 5],
        [1, 4, 6, 8, 2]]])

In [118]:
x.ndim


3

In [98]:
x.dot(x.T)

array([[164, 102, 111, 165, 123],
       [102,  94,  70, 112,  78],
       [111,  70, 138, 114,  93],
       [165, 112, 114, 175, 128],
       [123,  78,  93, 128,  97]])

In [99]:
inv(x)

array([[ 0.334     , -0.008     ,  0.07866667, -0.06866667, -0.36066667],
       [-0.16      , -0.08      ,  0.12      ,  0.48      , -0.44      ],
       [-0.074     , -0.112     , -0.06533333, -0.04466667,  0.36733333],
       [-0.012     ,  0.144     , -0.08266667, -0.09733333,  0.15866667],
       [-0.096     ,  0.152     ,  0.00533333, -0.44533333,  0.60266667]])

In [100]:
q,r=qr(x)

In [101]:
q

array([[-0.60246408,  0.77302764, -0.11454065,  0.10405475, -0.12457269],
       [-0.25819889, -0.33874245, -0.45526693,  0.7565813 ,  0.1972401 ],
       [-0.51639778, -0.38434239, -0.44851031, -0.62000392,  0.00692071],
       [-0.43033148, -0.36914241,  0.56015528,  0.17558688, -0.57787889],
       [-0.34426519, -0.06079993,  0.51446771, -0.0390095 ,  0.78203969]])

In [102]:
r

array([[-11.61895004, -11.01648596, -11.61895004, -11.96321522,
         -5.33611039],
       [  0.        ,  -3.41131016,   0.58628501,  -0.94022744,
         -2.70125388],
       [  0.        ,   0.        ,   3.95680046,   2.16115049,
         -2.12704569],
       [  0.        ,   0.        ,   0.        ,   7.3706772 ,
         -2.0052383 ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          1.29763223]])

In [103]:
np.diag(x)

array([7, 4, 4, 8, 2])

In [104]:
np.trace(x)

25

In [105]:
det(x)

1500.0

In [106]:
x,y=eig(x)

In [107]:
x #eigenvalues

array([23.58838167+0.j       , -1.72204963+3.0426909j,
       -1.72204963-3.0426909j,  3.25980822+0.j       ,
        1.59590937+0.j       ])

In [108]:
y #eigenvectors

array([[-0.51016082+0.j        ,  0.06907989-0.30569527j,
         0.06907989+0.30569527j, -0.62084132+0.j        ,
        -0.66138367+0.j        ],
       [-0.35287846+0.j        , -0.58773036+0.j        ,
        -0.58773036-0.j        ,  0.67047805+0.j        ,
        -0.11078261+0.j        ],
       [-0.43136166+0.j        ,  0.01788271+0.56882383j,
         0.01788271-0.56882383j, -0.27458774+0.j        ,
         0.40954301+0.j        ],
       [-0.51881996+0.j        ,  0.32813684-0.12842628j,
         0.32813684+0.12842628j,  0.2472843 +0.j        ,
         0.07667898+0.j        ],
       [-0.39995712+0.j        ,  0.25640259-0.20630479j,
         0.25640259+0.20630479j, -0.16872252+0.j        ,
         0.61375379+0.j        ]])

In [119]:
pinv(x)

array([[[-0.06378196,  0.17813993],
        [ 0.03456027, -0.02163529],
        [ 0.05113796, -0.02388311],
        [ 0.08569823, -0.0455184 ],
        [ 0.05254285, -0.04102276]],

       [[ 0.1061144 , -0.0504931 ],
        [ 0.04260355,  0.00946746],
        [-0.03155819,  0.06706114],
        [-0.03412229,  0.08500986],
        [ 0.09289941, -0.03491124]]])

In [120]:
from random import normalvariate
N=1000000


In [122]:
%time samples =[normalvariate(0,1) for _ in range(N)]

Wall time: 2.04 s


In [123]:
%time np.random.normal(size=N)

Wall time: 116 ms


array([ 0.80745314,  1.71819642, -0.38857614, ..., -0.37093592,
       -0.46844926,  0.13403835])

In [132]:
np.random.seed(1234)


In [134]:
rng=np.random.RandomState(1234)

In [135]:
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [136]:
#random walks

In [139]:
import random
import matplotlib.pyplot as plt
position=0
walk=[position]
steps=1000
for i in range(steps):
    step=1 if random.randint(0,1) else -1
    position+=step
    walk.append(position)

In [140]:
plt.plot(walk[:100])

In [160]:
position=0
walk=[position]
steps=1000
for i in range (steps):
        step=1 if random.randint(0,1) else -1
        position+=step
        walk.append(position)

In [164]:
walk

[0,
 1,
 2,
 3,
 4,
 3,
 2,
 3,
 2,
 1,
 0,
 -1,
 0,
 1,
 2,
 3,
 4,
 5,
 4,
 3,
 4,
 3,
 2,
 3,
 2,
 3,
 4,
 3,
 4,
 3,
 2,
 1,
 0,
 1,
 0,
 -1,
 -2,
 -3,
 -2,
 -3,
 -4,
 -3,
 -2,
 -1,
 -2,
 -1,
 -2,
 -1,
 -2,
 -3,
 -2,
 -1,
 -2,
 -3,
 -2,
 -1,
 -2,
 -1,
 -2,
 -1,
 -2,
 -1,
 0,
 -1,
 0,
 1,
 0,
 1,
 2,
 3,
 2,
 1,
 0,
 1,
 2,
 3,
 4,
 5,
 4,
 5,
 4,
 3,
 2,
 3,
 4,
 5,
 6,
 5,
 4,
 5,
 6,
 5,
 4,
 5,
 4,
 5,
 6,
 7,
 8,
 9,
 8,
 7,
 8,
 7,
 8,
 7,
 6,
 7,
 8,
 7,
 8,
 7,
 6,
 7,
 8,
 7,
 6,
 7,
 6,
 7,
 6,
 7,
 6,
 7,
 8,
 7,
 6,
 5,
 6,
 7,
 6,
 5,
 6,
 5,
 6,
 5,
 4,
 3,
 2,
 3,
 4,
 5,
 6,
 5,
 4,
 3,
 4,
 5,
 6,
 7,
 6,
 5,
 4,
 3,
 4,
 3,
 4,
 3,
 2,
 3,
 2,
 3,
 2,
 3,
 4,
 3,
 4,
 3,
 4,
 5,
 4,
 5,
 6,
 5,
 6,
 5,
 4,
 5,
 6,
 7,
 8,
 9,
 8,
 9,
 8,
 9,
 10,
 11,
 10,
 11,
 10,
 11,
 10,
 9,
 10,
 11,
 10,
 9,
 10,
 9,
 10,
 11,
 10,
 11,
 12,
 13,
 14,
 13,
 14,
 15,
 16,
 15,
 16,
 17,
 16,
 17,
 18,
 19,
 20,
 21,
 20,
 21,
 20,
 21,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15,


AttributeError: 'list' object has no attribute 'min'

array([[-0.41614198+0.j        , -0.73728161+0.j        ,
         0.28102843+0.j        , -0.19808661-0.36096007j,
        -0.19808661+0.36096007j],
       [-0.43424757+0.j        ,  0.25929272+0.j        ,
        -0.52049523+0.j        ,  0.3214943 -0.33880926j,
         0.3214943 +0.33880926j],
       [-0.52811947+0.j        , -0.26240749+0.j        ,
        -0.61412551+0.j        ,  0.11191555+0.39556939j,
         0.11191555-0.39556939j],
       [-0.39706696+0.j        ,  0.42475324+0.j        ,
         0.45494158+0.j        , -0.59273328+0.j        ,
        -0.59273328-0.j        ],
       [-0.4490908 +0.j        ,  0.3740456 +0.j        ,
         0.2568769 +0.j        ,  0.17427742+0.24822092j,
         0.17427742-0.24822092j]])