In [1]:
import pandas as pd
import numpy as np


df1=pd.DataFrame(np.random.randint(1,9,12).reshape(3,4),columns=list('abcd'),index=[1,2,3])
df2=pd.DataFrame(np.random.randint(1,9,20).reshape(4,5),columns=list('abcde'),index=[1,2,3,4])
df2

a  b  c  d  e
1  3  4  5  7  5
2  2  8  2  1  1
3  6  5  4  2  2
4  4  1  6  2  2

In [2]:
df1+df2

a    b     c     d   e
1  5.0  5.0  13.0  11.0 NaN
2  9.0  9.0   5.0   4.0 NaN
3  9.0  6.0   6.0  10.0 NaN
4  NaN  NaN   NaN   NaN NaN

In [3]:
df2.add(df1,fill_value=0)

a    b     c     d    e
1  5.0  5.0  13.0  11.0  5.0
2  9.0  9.0   5.0   4.0  1.0
3  9.0  6.0   6.0  10.0  2.0
4  4.0  1.0   6.0   2.0  2.0

In [4]:
df1.reindex(columns=df2.columns,fill_value=0)
df1.add(df2,fill_value=0)

a    b     c     d    e
1  5.0  5.0  13.0  11.0  5.0
2  9.0  9.0   5.0   4.0  1.0
3  9.0  6.0   6.0  10.0  2.0
4  4.0  1.0   6.0   2.0  2.0

In [5]:
df1.reindex(index=df2.index,fill_value=0)
df1.add(df2,fill_value=0)

a    b     c     d    e
1  5.0  5.0  13.0  11.0  5.0
2  9.0  9.0   5.0   4.0  1.0
3  9.0  6.0   6.0  10.0  2.0
4  4.0  1.0   6.0   2.0  2.0

In [6]:
df1.lt(4)

a     b      c      d
1   True  True  False  False
2  False  True   True   True
3   True  True   True  False

In [7]:
df2['a'].gt(2.0)

1     True
2    False
3     True
4     True
Name: a, dtype: bool

In [8]:
df2

a  b  c  d  e
1  3  4  5  7  5
2  2  8  2  1  1
3  6  5  4  2  2
4  4  1  6  2  2

In [9]:
f=lambda x:x.max()-x.min()
df2.apply(f,axis=1)

1    4
2    7
3    4
4    5
dtype: int64

In [10]:
def f(x):
    return pd.Series([x.argmin(),x.argmax()],index=['min','max'])


df2.apply(f)

a  b  c  d  e
min  1  3  1  1  1
max  2  1  3  0  0

In [11]:
format=lambda x:x**2

In [12]:
df2.applymap(format)

a   b   c   d   e
1   9  16  25  49  25
2   4  64   4   1   1
3  36  25  16   4   4
4  16   1  36   4   4

In [13]:
df4=pd.DataFrame(np.arange(12).reshape(4,3),index=['e','c','a','b'],columns=('Selma','Mara','Preet',))
df4

Selma  Mara  Preet
e      0     1      2
c      3     4      5
a      6     7      8
b      9    10     11

In [14]:
df4.sort_index()

Selma  Mara  Preet
a      6     7      8
b      9    10     11
c      3     4      5
e      0     1      2

In [15]:
df4.sort_index(axis=1)

Mara  Preet  Selma
e     1      2      0
c     4      5      3
a     7      8      6
b    10     11      9

In [16]:
df4.sort_index(axis=1,ascending=False)

Selma  Preet  Mara
e      0      2     1
c      3      5     4
a      6      8     7
b      9     11    10

In [17]:
df4.sort_index()


Selma  Mara  Preet
a      6     7      8
b      9    10     11
c      3     4      5
e      0     1      2

In [18]:
df4.sort_values(by=['Preet'])

Selma  Mara  Preet
e      0     1      2
c      3     4      5
a      6     7      8
b      9    10     11

In [19]:
df4.sort_values(axis=1,by='b')

Selma  Mara  Preet
e      0     1      2
c      3     4      5
a      6     7      8
b      9    10     11

In [20]:
df4.sort_values(axis=1,by='c')

Selma  Mara  Preet
e      0     1      2
c      3     4      5
a      6     7      8
b      9    10     11

In [21]:
s1=pd.Series(np.arange(6),index=['a','e','d','b','c','f'])

In [22]:
s1

a    0
e    1
d    2
b    3
c    4
f    5
dtype: int32

In [23]:
s1.sort_index()

a    0
b    3
c    4
d    2
e    1
f    5
dtype: int32

In [24]:
s1.sort_values()

a    0
e    1
d    2
b    3
c    4
f    5
dtype: int32

In [25]:
frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [26]:
frame.sort_values(by='b',ascending=False)

b  a
1  7  1
0  4  0
3  2  1
2 -3  0

In [27]:
frame.sort_values(by=['a','b'],ascending=False)

b  a
1  7  1
3  2  1
0  4  0
2 -3  0

In [28]:
frame.sort_values(by=['b','a'],ascending=False)

b  a
1  7  1
0  4  0
3  2  1
2 -3  0

In [29]:
obj=pd.Series(["c","a","d","a","a","b","b","c","c"])

In [30]:
obj.unique()


array(['c', 'a', 'd', 'b'], dtype=object)

In [31]:
obj.index.is_unique

True

In [32]:
pd.value_counts(obj.values,sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [33]:
mask=obj.isin(['b','c'])

In [34]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [35]:
to_match=pd.Series(["c","a","d","a","a","b","b","c","c"])

to_match.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [36]:
unique_values=pd.Series(['c', 'a', 'd', 'b'])

In [37]:
pd.Index(unique_values).get_indexer(to_match)

array([0, 1, 2, 1, 1, 3, 3, 0, 0], dtype=int64)

In [38]:
obj3=pd.Series([1,3,2,6,7,8,5,3,4,6,6])
obj3.unique()

array([1, 3, 2, 6, 7, 8, 5, 4], dtype=int64)

In [39]:
pd.value_counts(obj3.values,sort=True)

6    3
3    2
1    1
2    1
7    1
8    1
5    1
4    1
dtype: int64

In [40]:
match=pd.Series([1, 3, 2, 6, 7, 8, 5, 4])

In [41]:
pd.Index(match).get_indexer(obj3)

array([0, 1, 2, 3, 4, 5, 6, 1, 7, 3, 3], dtype=int64)

In [42]:
data=pd.DataFrame({'Qu1':[1,3,4,3,4],
                    'Qu2':[2,3,1,2,3],
                    'Qu3':[1,5,2,4,4]})

In [43]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [44]:
result=data.apply(pd.value_counts).fillna(0)

In [45]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [46]:
data1=pd.DataFrame({'Qu1':np.random.randint(1,9,20),
                    'Qu2':np.random.randint(1,9,20),
                    'Qu3':np.random.randint(1,9,20)})

In [47]:
data1

Qu1  Qu2  Qu3
0     8    3    2
1     1    4    1
2     2    4    6
3     3    8    6
4     8    6    6
5     6    5    8
6     7    3    6
7     5    3    5
8     8    1    4
9     1    2    2
10    2    3    4
11    2    1    7
12    1    6    7
13    4    8    8
14    8    6    7
15    6    6    6
16    2    7    6
17    4    4    7
18    2    7    3
19    3    4    7

In [48]:
result=data1.apply(pd.value_counts).fillna(0)

In [49]:
result

Qu1  Qu2  Qu3
1    3    2    1
2    5    1    2
3    2    4    1
4    2    4    2
5    1    1    1
6    2    4    6
7    1    2    5
8    4    2    2

In [50]:
result=data.apply(pd.value_counts).fillna(0)