In [4]:
import pandas as pd
import numpy as np

In [8]:
data=pd.DataFrame({"k1":["one","two"]*4+["two","two"],
                 "k2":[1,1,2,3,3,4,4,4,4,4]})

In [11]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  one   4
7  two   4
8  two   4
9  two   4

In [12]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8     True
9     True
dtype: bool

In [14]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  one   4

In [15]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  one   4
7  two   4
8  two   4
9  two   4

In [16]:
data.drop_duplicates(["k1"])

k1  k2
0  one   1
1  two   1

In [18]:
data.drop_duplicates(["k2"])

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [19]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  one   4
7  two   4
8  two   4
9  two   4

In [21]:
data["v1"]=np.arange(10)

In [22]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  one   4   6
7  two   4   7
8  two   4   8
9  two   4   9

In [25]:
data.drop_duplicates(["k1","k2"],keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  one   4   6
9  two   4   9

#transforming data using functions or mapping

In [27]:
data=pd.DataFrame({"food":["bacon","pulled pork","bacon","Pastrami","corned beef","Bacon","pastrami","honey ham","nova lox"], "ounces":[4,3,12,6,7.5,8,3,5,6]})

In [28]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [29]:
meat_to_animal={"bacon":"pig","pulled pork":"pig","pastrami":"cow","corned beef":"cow","honey ham":"pig","nova lox":"salmon"}

In [30]:
lowercased=data["food"].str.lower()

In [31]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [33]:
data["animal"]=lowercased.map(meat_to_animal)

In [34]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [35]:
data["animal"]=data["food"].map(lambda x:meat_to_animal[x.lower()])

In [36]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

#replacing values

In [38]:
data=pd.Series([1.,-999.,2.,-999.,-1000.,3.])

In [39]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [41]:
data.replace(-999.,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [42]:
data.replace([-999.,-1000.],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [43]:
data.replace([-999.,-1000.],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [44]:
data.replace({-999.:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [47]:
data=pd.DataFrame({"food":["bacon","pulled pork","bacon*","Pastrami","corned beef","Bacon","pastrami*12","honey ham","nova lox"], "ounces":[4,3,12,6,7.5,8,3,5,6]})

In [48]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2       bacon*    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6  pastrami*12     3.0
7    honey ham     5.0
8     nova lox     6.0

In [51]:
data["food"].str.replace("[\*\d]*","")

0          bacon
1    pulled pork
2          bacon
3       Pastrami
4    corned beef
5          Bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

#Renaming Axis Indexes

In [64]:
data=pd.DataFrame(np.arange(12).reshape((3,4)),index=["Ohio","Colorado","New York"],columns=["one","two","three","four"])

In [65]:
transform=lambda x:x[:4].upper()

In [68]:
data.index=data.index.map(transform)

In [69]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [73]:
data=pd.DataFrame(np.arange(12).reshape((3,4)),index=["Ohio","Colorado","New York"],columns=["one","two","three","four"])

In [74]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [76]:
data.rename(index={"Ohio":"Indiana"},columns={"three":"peekaboo"})

one  two  peekaboo  four
Indiana     0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

In [78]:
data.rename(index={"Ohio":"Indiana"},inplace=True)

In [79]:
data

one  two  three  four
Indiana     0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

# Discretization and Binning

In [97]:
ages=[16,17,20,22,25,27,89,21,23,37,31,61,45,41,32]

In [98]:
bins=[14,18,25,35,60,100]

In [99]:
cats=pd.cut(ages,bins)

In [100]:
cats

[(14, 18], (14, 18], (18, 25], (18, 25], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 15
Categories (5, interval[int64]): [(14, 18] < (18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [101]:
cats.codes

array([0, 0, 1, 1, 1, 2, 4, 1, 1, 3, 2, 4, 3, 3, 2], dtype=int8)

In [102]:
cats.categories

IntervalIndex([(14, 18], (18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [104]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    2
(14, 18]     2
dtype: int64

In [106]:
numbers=[2,3,4,5,6,12,15,16,17,18,20,22,26,28,31,33,45,41,56,57,77,67,88,62,91]

In [110]:
bins=[1,10,20,30,40,50,60,70,80,90,100]

In [119]:
cats=pd.cut(numbers,bins,right=False)

In [120]:
cats

[[1, 10), [1, 10), [1, 10), [1, 10), [1, 10), ..., [70, 80), [60, 70), [80, 90), [60, 70), [90, 100)]
Length: 25
Categories (10, interval[int64]): [[1, 10) < [10, 20) < [20, 30) < [30, 40) ... [60, 70) < [70, 80) < [80, 90) < [90, 100)]

In [121]:
cats.codes

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 4, 4, 5, 5, 7, 6,
       8, 6, 9], dtype=int8)

In [122]:
cats.categories

IntervalIndex([[1, 10), [10, 20), [20, 30), [30, 40), [40, 50), [50, 60), [60, 70), [70, 80), [80, 90), [90, 100)],
              closed='left',
              dtype='interval[int64]')

In [123]:
#pd.value_counts(cats) are the bin counts for the result od pandas.cut

In [124]:
pd.value_counts(cats)

[10, 20)     5
[1, 10)      5
[20, 30)     4
[60, 70)     2
[50, 60)     2
[40, 50)     2
[30, 40)     2
[90, 100)    1
[80, 90)     1
[70, 80)     1
dtype: int64

In [140]:
ages=[16,17,20,22,25,27,89,21,40,23,37,31,61,45,41,32]
bins=[14,18,25,35,60,100]

In [141]:
group_names=["Teenage","Youth","YoungAdult","MiddleAged","Senior"]

In [142]:
cats=pd.cut(ages,bins,labels=group_names)

In [143]:
cats

[Teenage, Teenage, Youth, Youth, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 16
Categories (5, object): [Teenage < Youth < YoungAdult < MiddleAged < Senior]

In [144]:
pd.value_counts(cats)

Youth         5
MiddleAged    4
YoungAdult    3
Senior        2
Teenage       2
dtype: int64

In [145]:
cats.codes

array([0, 0, 1, 1, 1, 2, 4, 1, 3, 1, 3, 2, 4, 3, 3, 2], dtype=int8)

In [146]:
cats.categories

Index(['Teenage', 'Youth', 'YoungAdult', 'MiddleAged', 'Senior'], dtype='object')

In [147]:
data=np.random.rand(20)

In [148]:
cats=pd.cut(data,4,precision=2)

In [150]:
cats.codes

array([2, 3, 3, 1, 3, 0, 1, 3, 1, 3, 0, 3, 1, 3, 0, 3, 1, 1, 2, 1],
      dtype=int8)

In [151]:
cats.categories

IntervalIndex([(0.051, 0.28], (0.28, 0.51], (0.51, 0.73], (0.73, 0.96]],
              closed='right',
              dtype='interval[float64]')

In [152]:
pd.value_counts(cats)

(0.73, 0.96]     8
(0.28, 0.51]     7
(0.051, 0.28]    3
(0.51, 0.73]     2
dtype: int64

#qcut: uses sample quantile,results in roughly equal-size bins

In [154]:
data=np.random.randn(1000) #Normally distributed

In [155]:
cats=pd.qcut(data,4) #cut into quartiles

In [156]:
cats

[(-3.433, -0.666], (-3.433, -0.666], (-3.433, -0.666], (-3.433, -0.666], (-3.433, -0.666], ..., (-0.666, 0.0394], (0.742, 3.839], (0.742, 3.839], (-0.666, 0.0394], (-0.666, 0.0394]]
Length: 1000
Categories (4, interval[float64]): [(-3.433, -0.666] < (-0.666, 0.0394] < (0.0394, 0.742] < (0.742, 3.839]]

In [157]:
cats.codes

array([0, 0, 0, 0, 0, 1, 0, 2, 3, 2, 0, 2, 0, 0, 1, 3, 0, 2, 1, 1, 2, 3,
       3, 0, 1, 1, 1, 0, 2, 2, 1, 1, 2, 0, 2, 1, 1, 2, 0, 1, 1, 2, 3, 3,
       2, 1, 0, 0, 3, 2, 1, 2, 2, 1, 0, 2, 2, 1, 0, 1, 3, 0, 0, 2, 3, 3,
       0, 3, 2, 0, 2, 2, 3, 3, 1, 3, 0, 3, 0, 1, 0, 1, 3, 2, 1, 0, 2, 2,
       2, 1, 2, 2, 3, 1, 3, 2, 3, 2, 1, 0, 0, 3, 2, 2, 3, 2, 0, 3, 0, 2,
       2, 3, 3, 2, 0, 3, 3, 1, 1, 1, 0, 2, 1, 1, 2, 3, 3, 2, 2, 2, 1, 0,
       3, 0, 2, 2, 3, 0, 3, 0, 3, 0, 0, 0, 3, 3, 1, 0, 1, 2, 1, 1, 3, 0,
       0, 0, 0, 2, 2, 1, 0, 3, 1, 3, 3, 3, 0, 2, 2, 2, 1, 2, 0, 1, 0, 1,
       3, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2, 0, 0, 0, 0, 1, 2, 3, 0, 3, 0,
       0, 1, 2, 3, 0, 3, 2, 1, 3, 3, 2, 1, 3, 3, 1, 0, 3, 3, 3, 1, 2, 3,
       0, 1, 0, 1, 3, 2, 1, 1, 0, 2, 1, 3, 0, 3, 3, 2, 0, 0, 2, 3, 3, 3,
       0, 2, 3, 2, 0, 0, 2, 2, 3, 2, 0, 2, 1, 0, 3, 2, 3, 0, 0, 1, 1, 0,
       1, 0, 1, 2, 0, 2, 3, 0, 1, 3, 2, 0, 0, 0, 0, 2, 2, 1, 0, 3, 3, 1,
       2, 0, 0, 2, 0, 0, 1, 2, 0, 3, 2, 1, 0, 1, 2,

In [158]:
cats.categories

IntervalIndex([(-3.433, -0.666], (-0.666, 0.0394], (0.0394, 0.742], (0.742, 3.839]],
              closed='right',
              dtype='interval[float64]')

In [159]:
pd.value_counts(cats)

(0.742, 3.839]      250
(0.0394, 0.742]     250
(-0.666, 0.0394]    250
(-3.433, -0.666]    250
dtype: int64

#similarly to cut we can pass our own quantiles(numbers between 0 and 1,inclusive)

In [169]:
pd.qcut(data,[0,0.1,0.5,0.9,1])

[(-1.238, 0.0394], (-3.433, -1.238], (-3.433, -1.238], (-3.433, -1.238], (-1.238, 0.0394], ..., (-1.238, 0.0394], (0.0394, 1.235], (1.235, 3.839], (-1.238, 0.0394], (-1.238, 0.0394]]
Length: 1000
Categories (4, interval[float64]): [(-3.433, -1.238] < (-1.238, 0.0394] < (0.0394, 1.235] < (1.235, 3.839]]

In [170]:
pd.value_counts(cats)

(0.742, 3.839]      250
(0.0394, 0.742]     250
(-0.666, 0.0394]    250
(-3.433, -0.666]    250
dtype: int64

#Detecting and filtering Outliers:It is largely a matter of applying array operations.

In [219]:
data=pd.DataFrame(np.random.randn(1000,4))

In [220]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.005833    -0.036331     0.042004     0.007601
std       1.006492     1.006464     1.015835     1.037495
min      -3.108594    -3.383209    -2.780154    -3.213101
25%      -0.674251    -0.714976    -0.659085    -0.675755
50%       0.038474    -0.012359     0.052709     0.002910
75%       0.645260     0.637507     0.711264     0.702460
max       2.794501     2.949909     3.451307     3.728391

In [221]:
col=data[1]

In [222]:
col[np.abs(col)>3]

4    -3.383209
83   -3.237398
Name: 1, dtype: float64

In [223]:
col=data[2]

col[np.abs(col)>2.9]

563    3.451307
643    2.905504
Name: 2, dtype: float64

In [224]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
4    0.401790 -3.383209  0.943545  0.321238
65  -1.702126  0.058650 -0.832892 -3.213101
83   0.141447 -3.237398 -1.439132 -1.186538
228 -1.870950 -0.575918  0.819027  3.012413
258  0.365148 -0.000212  0.841011  3.728391
462 -3.108594  1.319525  1.330941  0.848079
563 -0.155994 -1.394715  3.451307  0.764305
808  1.236838  1.996385 -1.721936  3.194670

In [225]:
data.head()

0         1         2         3
0  1.247696 -0.137328 -1.527146  1.404068
1  0.480713 -1.030296  1.326817 -0.186205
2 -1.805041 -0.668339 -0.308566  0.040850
3  0.453460 -1.167044 -0.099782  1.254058
4  0.401790 -3.383209  0.943545  0.321238

In [226]:
np.sign(data)*3

0    1    2    3
0    3.0 -3.0 -3.0  3.0
1    3.0 -3.0  3.0 -3.0
2   -3.0 -3.0 -3.0  3.0
3    3.0 -3.0 -3.0  3.0
4    3.0 -3.0  3.0  3.0
..   ...  ...  ...  ...
995  3.0  3.0  3.0  3.0
996 -3.0 -3.0 -3.0 -3.0
997  3.0  3.0  3.0  3.0
998 -3.0 -3.0 -3.0 -3.0
999  3.0 -3.0 -3.0 -3.0

[1000 rows x 4 columns]

In [ ]:
#filtering all values greater than abs 3(+3 and -3) are filtered out

In [227]:
data[(np.abs(data)>3)]=np.sign(data)*3

In [228]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.005725    -0.035711     0.041553     0.006878
std       1.006163     1.004532     1.014418     1.033873
min      -3.000000    -3.000000    -2.780154    -3.000000
25%      -0.674251    -0.714976    -0.659085    -0.675755
50%       0.038474    -0.012359     0.052709     0.002910
75%       0.645260     0.637507     0.711264     0.702460
max       2.794501     2.949909     3.000000     3.000000

#Permutation and Random Sampling

In [230]:
df=pd.DataFrame(np.arange(5*4).reshape(5,4))

In [231]:
df.head()

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [233]:
sampler=np.random.permutation(5)

In [234]:
sampler

array([0, 2, 3, 1, 4])

In [235]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7
4  16  17  18  19

In [236]:
df.sample(n=3)

0   1   2   3
0   0   1   2   3
4  16  17  18  19
1   4   5   6   7

In [237]:
choices=pd.Series([5,7,-1,6,4])

In [238]:
draws=choices.sample(n=10,replace=True)

In [239]:
draws

4    4
3    6
3    6
1    7
1    7
2   -1
4    4
2   -1
0    5
0    5
dtype: int64

In [243]:
draws=choices.sample(n=20, replace=True)

In [244]:
draws

0    5
3    6
1    7
0    5
0    5
2   -1
3    6
0    5
4    4
0    5
3    6
0    5
4    4
1    7
3    6
4    4
0    5
2   -1
3    6
2   -1
dtype: int64

#Computing Indicators/Dummy Variable:converting categorical values into "dummy" or "Indicator" matrix.

In [246]:
df=pd.DataFrame({"key":["b","b","a","c","a","b"],"data1":range(6)})

In [247]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [248]:
pd.get_dummies(df["key"])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [250]:
dummies=pd.get_dummies(df["key"],prefix="key_")

In [251]:
dummies

key__a  key__b  key__c
0       0       1       0
1       0       1       0
2       1       0       0
3       0       0       1
4       1       0       0
5       0       1       0

In [252]:
df_with_dummies=df[["data1"]].join(dummies)

In [253]:
df_with_dummies

data1  key__a  key__b  key__c
0      0       0       1       0
1      1       0       1       0
2      2       1       0       0
3      3       0       0       1
4      4       1       0       0
5      5       0       1       0